name: file_converter_app
description: Ultimate File Converter Pro - Developed by Muhammad FaheeM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Document Scanning
  cunning_document_scanner: ^1.4.0
  flutter_doc_scanner: ^0.0.16
  
  # Image Format Conversion
  image: ^4.2.0
  platform_image_converter: ^1.0.6

  # PDF Handling
  pdf: ^3.11.0
  pdf_combiner: ^1.0.0
  native_pdf_renderer: ^5.0.0+1
  printing: ^5.13.0

  # GIF Creation
  gify: ^1.0.9

  # Utilities
  path_provider: ^2.1.4
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  flutter_image_compress: ^2.3.0
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#2196F3"
  image: assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/